#+TITLE: Wu-Wei

Wu-Wei is a personal productivity platform written in ClojureScript.

* Highlights

* Installation

* Usage

* Ideological Approach

The following values exist in roughly sorted order.

** Keep the Project Enjoyable to Extend and Develop

It is engineering heresy to prioritize the implementation details of a
product above the product itself. However, that is what I intend to do
here. I have a few reasons for this.

First, there are plethora of existing options out there for both task
management and personal knowledge management. Many of these are
well-supported, thoroughly monetized, and widely-adopted. I do not
anticipate or aspire for Wu-Wei to displace the market share of any of
these solutions. Mass-market appeal is specifically excluded as a goal
of this project.

Rather, I am writing this primarily for my own use, based on my
experiences and frustrations with other solutions. I also expect that
there are many others like myself who will also enjoy using Wu-Wei,
and appreciate these same implementation choices, which are uniquely
unavailable in competing products.

*** Lisp

Of these implementation decisions, the one closest to my heart is the
use of Lisp for both the frontend and backend. Lisp supports joyful
and rapid coding, and this makes it especially well-suited to software
projects written by volunteers in their spare time. Right now, Wu-Wei
uses the Clojure programming language -- a Lisp dialect -- due to the
exceptional maturity of the Clojurescript ecosystem. That being said,
I would not be against the use of other Lisp dialects (particularly
Common Lisp) should they be more appropriate down the road.

*** FOSS

The second critical implementation detail of Wu-Wei is that it shall
be open source. Personal organization systems quickly become integral
to one's routine. They will invest hundreds of hours configuring and
populating these systems with every detail of their daily lives. To
hold this information captive in a system which cannot be modified,
reproduced, extended, or meaningfully debugged by oneself is, in my
opinion, abhorrent.

*** Self-Hosting

Wu-Wei will cater to individuals and teams who prefer on-site
deployment, which keeps all of their personal information on their own
local machines.

** Scale Complexity with Need

The features and abstractions that make advanced roadmapping possible
within Wu-Wei should not impose overhead or burden on more simple
projects which do not need these things.

A new Wu-Wei account should look and behave like any other trivially
simple to-do list application. Scheduling, effort estimates, recursive
subtask browsing, and so on, should be obviously available, but out of
the way until they are wanted.

** Support a Getting Things Done (GTD) Approach by Default

This is not the only workflow eligible for support, but, it will be
given special attention whenever design decisions are made. New users
will be given an inbox, shown the capture system, and encouraged to
sort their inbox periodically. A Task status of "Next" will be
available by default, and so on.

** Server/Client Architecture

Even the best organization system is useless if you cannot access
it. A primary goal of Wu-Wei is to be fully available anywhere that a
web browser is available.

** Separate Keyboard and Touch Interfaces

Wu-Wei will have two no-compromise interfaces. One optimized for
keyboard and mouse interaction, and a separate interface for
touchscreens and on-screen keyboards. There is no practical benefit to
a single user interface that attempts to provide half-assed support to
both use-cases, and Wu-Wei will not venture down that path.

* Brainstorm, Requirements, Roadmap

** Top-Level Views

Plan, Do, Document

*** Tasking & Execution Roadmapping

Tasks are created, organized, and edited here.

**** Expand a task to full-screen

Use a bottom-left / top-right square icon?

Floating over main content? Start showing a lot of advanced features here.

*** Calendar & Time Tracking

Work for tasks is scheduled, deadlines illustrated, and effort-spent
can be tracked here.

*** Note-Taking and PKMS

Depot for information relevant to tasking.

** Decomposition of Tasks into Subtasks as a Core Abstraction

Subtasks should not be an afterthought in Wu-Wei, as they are in Jira
and many other task management solutions. The data structures and user
interfaces should consider deeply nested subtasks as a primary
use-case, and they should be just as easy to use and understand as
top-level tasks.

Nesting tasks provides a way of edifying the relationship between "Big
Tasks" and "Small Tasks". Specifically, that Big Tasks are composed of
increasingly smaller but more detailed, subtasks. This composition
relationship is recursive, and the depth of the recursion depends
entirely on the project, and, how the user prefers to decompose their
work.

*** Recursing Into Tasks in Task List

One realization of this is in the UI, where tasks can be 'recursed'
into. When this is done, the task list will be replaced with only
subtasks of the task that was recursed into. The recursed task will be
added to the context stack above the list, providing clear feedback to
the user of "where they are" within the scope of the project. The
context stack is a breadcrumb that explains to the users the
high-level significance of the tasks that they are currently
editing. It brings the "why" into the "what".

Direct children of recursed task are listed in group at top of
list. Indirect descendents are grouped together in a second set.

*** Trees?

? Should there be a "tree view" that shows all paths for a Big Task?
Each path is a path through the tasks / through the requirements to
completion. Finding this path of least resistance is the point of Wu
Wei.

? Should we force the composition to be acyclic?

? Can tasks be subtasks of multiple parents?

** Critical Path Analysis

When a task and its subtasks have effort estimates, critical path
analysis could be available. This can be shown as the longest sequence
from current task to any leaf beneath it. The times of all other paths
can also be calculated, and shown at the leaf nodes.

? Doesn't this require :or, :any, :all, etc relationships between
tasks to really work well? Seems messy. Need a UI solution for this.

** Remove mental burden, help decide priorities & choose where to work

Filter that shows all "unblocked leafs" for a Big Task. IE, here are
the things you can do right now.

Also filter to show all blocked leaves, and their blockers, for a Big
Task.

** Task Filtering, Sorting?

Only mine, blocked, unblocked, etc

Advanced filtering with EDN syntax [:and :blocked [:not :mine]]

For recursive tasks, view only direct subtasks (or parents) or all
generations, or up to a limit.

Sort task subtask tree BFS and DFS? Only if not splitting them. Or
maybe apply specifically to the indirect section/

** Time tracking and effort estimates

Use calendar to schedule chunks of work on tasks. Same UI to log work
completed for time-tracking.

Graphs to show effort, focus over time?

** Due Dates, Milestones

Use effort-estimate and due-date to show warnings to user when
unstarted tasks are at risk of not completing. Use color, exclamation
points to highlight these in the task list?

Every task's due-date, start-date, etc is a milestone. You can use
these to in cross-task dependencies to keep them aligned. IE, start
task B when task A completes, regardless of when that is.

Standalone milestones can be defined, used as values for
due-dates. For example, Q2 Release Cycle cna be a top-level task
created for milestones only. It can be decomposed into subtasks that
depend on each others due-dates (implementation, integration, testing
phases, for example). These milestones can then be used by other
top-level tasks & their compositional subtasks.

? Should milestone tasks use calendar time and not effort? How would that work?

** History

Git-based built-in history may be technically infeasible, but I do
think the full revision history of all tasks and notes should be
accessible.

Tasks should be able to show who changed the status of the task, and
on which date, for every status transition. This makes it
auditable. It should also be able to show which changes were made to
summary, description, and so one for each editing transaction.

Beyond the task view, there could be a timeline view that allows users
to see what they did each day. Marking particular edits, working on
particular tasks, documenting certain projects, etc. Higher-level
tools or features could use this to illustrate shifting focuses over
time. This can be a useful tool in passively understanding how time
was allocated in the past.

** Export & Interop

Export to both easily tooled formats (JSON, EDN) and human readable
(HTML, org-mode, etc) are high priority.

Import from other systems a nice to have (especially TickTick and
org-mode, since I use them).

External integrations (DAV, Google Calendar and similar) are lowest
priority.

** Extensibility

TBD. Would like end-users to be able to customize their user interface
with custom lisp without rebuilding the application (like init.el in
emacs), but I am not sure how technically feasible this
is. Clojurescript has some degree of self-hosting, but practicality
will determine how we far we get with this.

If nothing else, make complete and advanced configuration via EDN
possible. Users can share fragments of their EDN config. Maybe permit
things not possible with general UI.

** Notebooks

Notebooks separate like lists

But content inside notebooks not paginated -- just decomposed by
heading. Can click on a treeview menu to navigate, but still
essentially all one "page". Rely on good recursion handling to make
this not distracting or laborious.

*** Today Page / Journal

Each day gets their own page for "unsorted" content. This is like a
capture system. Headings here can be "resorted" into more appropriate
notebooks, just like in org mode.

Navigate using small calendar in sidebar. Special since most notebooks
navigate with tree menu.

idea: Can the journal page automatically aggregate all changes made
anywhere in the system on that day? Maybe this aggregation can be
"irrevocable" or canonical, and the journal is the key mechanism that
prevents orphaned blocks? IE all content not in journal is just a
'reference' to the content in journal?

** Markup for task bodies and notes

Do a subset of something reasonable, maybe Org. There's a nice
analogue between Clojure metadata and Org property drawers that we can
work with.

*** Recursion in Notes
Each "chunk" of text in a note should be a standalone thing under a
heading. When scrolling, headings should maintain a context stack,
just like the task list. Very similar to how functions etc are handled
in vscode scrolling as well.

? Heading font size, etc, could remain relative to whatever is
in-view? IE a heading at indentation level 4 could appear like H1 if
it is the most general heading shown.

? Task bodies are "text blocks" just like headings within note books?

? Are tasks a superset of text blocks? This could be powerful. Use
case: When taking daily notes, use an inline command or key combo to
convert heading to a task by adding a "status" property to the
property drawer. Instantly makes it accessible to the task
list. Basically, duck-type the difference between text blocks and
tasks based on their 'metadata' having a status field? hmm

*** Inline Commands

Should work in notes similarly to in the task creation box, where it
makes sense

Example: /+task:Go to the store/ adds a task and leaves no trace in
the original text

But with $ in place of /, will leave a link: $+task:Go to the store$
performs action and self-replaces with link syntax to the new task.

command ideas:
- +task: create a task
- task: link to a task interactively
- schedule: schedule task being edited
- assign: assign task to new owner
- refile: move to new location

*** Linking between text blocks, tasks, etc

Use some syntax for this.

Each element will need a unique ID. Support "tagging" or labeling
manually for easier reference? Or, generate meaningful unique tags by
default based on context?

** Habits and Recurring Tasks

Some special case of the status field. Maybe different than normal
tasks. Not sure yet but this is an important use case to get right.

Need repetition history easily accessed and viewed.

** Configurable things

Task statuses (TODO, in progress, next, blocked, done, etc), colors for each status, and legal status transitions as an adjacency matrix?

Mandatory task properties? assignee, effort, etc

Settings that apply only to certain lists? Setting overrides per task? Setting overrides per task subtree? EDN data in the task drawer?

** Kanban view?

Transition status (or other field?) of tasks/entities via a column view

** Split User Interfaces

*** Desktop

Can move/restruture via click and drag on handle on tasks or nodes (alt to move subtree?)

Should support multiple view panes with arbitrary content? Allow
agenda & notes side by side? What about floating windows?

*** Touch

How to move tasks? Clipboard?

** Other & Stretch

Don't forget a dark mode

Grep-like full-text real-time regex search across all content in the system.

Able to add other resources (like PDFS?), index them for search, and
link to them from notes/tasks.

Multiuser support with collab editing for notes, tasks, assignment, etc.

Maybe a "watch list" or shortcut / bookmark list on the left back on the task view?

A "today" view that collects things due soon or today? Or scheduled to be done today?

A different "today" view where users can collect backlog items that they plan to do today?

Template tasks?

Template subtrees? Template project roadmaps?

Grouping or organizing lists into folders?

Mosaic view -- tasks and subtasks drawn recursively in nested frames. Area of each task proportional to its subtree effort. Like windirstat. Show text in each square.

Integration of a screencap tool

Browser bookmarks, maybe via browser extension?

Is time since assigment (or, time assigned to user/resource) a useful thing to show?

Allow entities to be 'tagged' with canonical names for easier reference / permalinks?

Built-in browser feels excessive (and difficult with browser-based client due to CORS -- but proxy through server could work, and, enable a 'free' VPN?). But what about a dedicated Wikipedia client?

Of course, an LLM

*** JIRA backend / interop?

Lists are epics? Maybe?

* Competitor Analysis / Breakdown

Let's make sure I understand how others are solving these problems before reinventing the wheel.

For each, cover:
- ideology
- scope (tasks, notes, roadmapping, time tracking, habits, etc)
- architecture (server/client, single machine?)
- team-oriented, individual only, or both?
- user interface
- features
- weaknesses
- data storage (flat file? database?)
- FOSS?

Classes of Competition
- PKMS (Notion, obsidian)
- Kanban (Trello)
- Roadmapping
- Pomodoro / Time Trackers / Time blocking / Focus Helpers
- Habit / "clickers" / Routine management

** org-mode in emacs

The absolute GOAT. Supports everything. Infinitely extensible.

*** Unique Strengths

The text is the canonical data.

org-babel

*** Weaknesses

The text is the canonical data. It's painful to develop for org-mode
(IMO) because you constantly have to parse text, and hope there are
existing parse functions for most of what you want to do. And
org-syntax is notoriously not easy to parse correctly (unless you
accept a subset of the markup). You /can/ extend org to do anything,
but, that doesn't mean you'll want to.

If you don't have /your/ laptop in front of you, org is essentially
useless. Yes, there's Orgzly, but it is a far cry from the real
thing. It's also keyboard or nothing. God help the man using org-mode
on a tablet.

it gets slow quickly with large org file directories. My org-agenda
took 2-3 minutes to refresh after just a couple years of use. And
yeah, maybe I could be better about tidying things up, but I did not
have enough content that a modern task management software should
already be choking.

Single-user / single machine. Having all data in human-readable flat
files makes file syncing and version control very doable with external
tools though. I've had luck syncing my org directory with Seafile, and
reving it with Git.

** TickTick

Nothing special but it "Just Works" extremely well. Great example of a
solution that makes itself compelling by limiting its scope as much as
possible, without becoming useless.

** Todoist

** Clickup

** Asana

** Jira + Structure, etc

** Everdo

** Notion

** Lotus Notes

** Yoodoo

** Task Warrior

** Timebloc

** Wrike

** Microsoft TODO

** Google Keep

** Monday.com

** Google Tasks

** Any.do

** Trello

** Zoho

** Roam

** Evernote

** Obsidian

** Joplin

** Zim

** Capacities

The object system is very unique and seems very close to how I'd like
to handle notes vs tasks vs other resources in Wu-Wei. I need to learn
more about how types work in Capacities.

** Hypernotes

** Logseq

*Wow* -- I had not heard of this before doing this 'competitor
analysis'. Logseq hits very close to the mark in terms of
implementation details.

*** Overview

Primarily an outlining app. Each chunk of text is a block. Blocks can
be bidirectionally linked throughout the application. There's a graph
view of all blocks and links.

*** Initial Impressions

It's interesting, seems very powerful. Discoverability is a little
low. Had to google to see all "open" todo tasks (graph view -> LATER).

I wonder if the graph view becomes an incomprehensible mess after a
few years? -- update: have seen feedback that the graph view is not as
useful so much as it is neat to look at.

One thing I notice and like is that it uses daily journal pages by
default. This is how I have configured my org-mode to work, and it is
very effective. Extensions for tasking and capture slap new headings
in here, just like org does.

*** Strengths

org-like note taking syntax and extensions (#+BEGIN_ etc)

Graph-like relationship between entities, just as is planned for
Wu-Wei

Supports plugins/extensions

It's /even written in Clojure/

*** Weaknesses

Single-user. Local only (though it can sync with
extensions?). Mutliuser is coming as a paid feature.

Not sure of mobile apps / Touch UI. People seem to feel that the
mobile apps are second class citizens, not well liked.

Appears that task management is an ancillary feature, but extensions
could build upon this.

*** Tasking

Tasks are sort of bolted-on, with statuses being blocks themselves
that appear in the graph. This might feel academically satisfying to
someone but I don't understand how it is practical. Extensions may
improve the experience here.

*** Data Storage

local-first with a sync service

Stores data locally as markdown or org-mode files, though apparently
there's also "graph DB (SIC)" that might be backed by a SQL (sqlite?)
database somehow. There's also a "DB version" in development that will
support collaborative editing. Unclear on details here, need to sit
down and focus on this.

*** Revisioning

Uses git under the hood, appears to be packaged with it. Advanced
settings permit autocommits, etc. Snazzy.

*** Markup

"#thing", "[[thing] ]" and "#[[thing] ]" are all the same, except in
how they appear. At least in Markdown files. Clicking one opens a new
page by that name. Not actually created til content added.

*** Media

Can attach files, including audio/video/image and PDF. PDFs
specifically can be viewed and annotated within the application. This
is a killer feature.

*** User Interface

Minimalist, maybe too much so. Definitely goes for the "blank canvas"
vibe. Does support dual-pane. Has a menu bar. Extensions can add more
elements (tabs, etc).

When the cursor is placed in a block, it is unrendered and raw
markdown is shown. Rendered markdown is shown when focus exits the
block. This might be why new blocks are created with every line break.

*** Other

I like how hovering over links shows a preview of the linked page.

I like how pages have a 'references' section at the bottom, with
/timestamped/ events.

Tags for headings are inherited from parent headings, as they are in
org-mode. I haven't always found this behavior to be sensible in my
org-mode workflows but I understand why it makes some sense.

One of my issues with org is that the text-file based data store is
very slow to process. Logseq appears to have this issue too to some
degree -- videos on Youtube show quite long startup times for the app
when users have a lot of content.

Blocks have UUIDs for linking -- and there are a lot of blocks, since
each new-line generates one by default. Would prefer Wu-Wei to be more
like org-mode, where headings are only created with intentional
asterisks.

Massive plugin ecosystem.

Pretty buggy. Frequently found that I could not edit blocks. CSS
editor doesn't work either.

** OneNote

Objectively sucks for managing tasks and is mediocre at best at being
a shared knowledgebase. But it does work for both, speaking from
unfortunate personal experience.

** Outline

** SiYuan

A rare self-hosted open source option. Looks actually pretty
promising.

** Craft App

** coda.io

Lots of integrations?

** Draft

** Amplenote

** Athens

Dead but this was in Clojure too

** Miro

** Airtable

** Dendron

** Affine.pro

** Quip

** Remote

** BookStack
